name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Version Name
        id: version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: |
            profile=prod
          context: .
          tags: sadatul/hackathon_authservice_prod:${{ steps.version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: "kubernetese-cluster-prod"
          location: "asia-southeast1-a"
      - run: kubectl config get-contexts
      - name: Install Kluctl
        run: curl -s https://kluctl.io/install.sh | bash
      - name: Replace Image
        run: sed -i "s/<!IMAGE>/${{ needs.build.outputs.version }}/g" config/prod.yaml
      - name: Deploy with Kluctl
        working-directory: deploy
        continue-on-error: true
        run: kluctl deploy -t prod -y

